name: Set Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to set"
        required: true
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  set-version:
    name: Set Version
    permissions:
      contents: write
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # 6.3.0
        with:
          node-version: lts/*
          check-latest: true

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # 5.0.0
        with:
          version: latest

      - name: Set package version
        run: pnpm version --no-git-tag-version --allow-same-version ${INPUTS_VERSION}
        env:
          INPUTS_VERSION: ${{ inputs.version }}

      - name: Commit version
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # 7.1.0
        with:
          commit_message: "chore(release): bump version to ${{ inputs.version }}"
