name: Test

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  test:
    name: Build and Test

    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # 5.0.0
        name: Install pnpm
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: lts/*
          cache: 'pnpm'
          check-latest: true

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: |
          pnpm typecheck

      - name: Run check
        run: |
          pnpm exec biome ci

      - name: Run web build
        run: |
          pnpm build:web
